"""Stage 4 — Export: write enriched CSV, SQLite database, and HTML report."""

import logging
import sqlite3
from datetime import datetime
from pathlib import Path

import pandas as pd
from jinja2 import Template

log = logging.getLogger(__name__)

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DataSift Pipeline Report — {{ pipeline_name }}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           background: #f8fafc; color: #1e293b; padding: 32px; }
    .header { background: linear-gradient(135deg, #6366f1, #8b5cf6);
              color: white; padding: 32px; border-radius: 12px; margin-bottom: 24px; }
    h1 { font-size: 28px; font-weight: 700; }
    .subtitle { opacity: 0.85; margin-top: 4px; }
    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
             gap: 16px; margin-bottom: 24px; }
    .card { background: white; border-radius: 10px; padding: 20px;
            box-shadow: 0 1px 4px rgba(0,0,0,0.08); text-align: center; }
    .card-value { font-size: 36px; font-weight: 700; color: #6366f1; }
    .card-label { font-size: 13px; color: #64748b; margin-top: 4px; }
    .section { background: white; border-radius: 10px; padding: 24px;
               box-shadow: 0 1px 4px rgba(0,0,0,0.08); margin-bottom: 20px; }
    h2 { font-size: 18px; font-weight: 600; margin-bottom: 16px; color: #334155; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #f1f5f9; padding: 10px 14px; text-align: left;
         font-weight: 600; color: #475569; border-bottom: 1px solid #e2e8f0; }
    td { padding: 9px 14px; border-bottom: 1px solid #f1f5f9; color: #374151; }
    tr:last-child td { border-bottom: none; }
    .bar-wrap { background: #f1f5f9; border-radius: 4px; height: 10px; overflow: hidden; }
    .bar { background: #6366f1; height: 100%; border-radius: 4px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px;
             font-size: 11px; font-weight: 600; }
    .badge-green { background: #dcfce7; color: #16a34a; }
    .badge-red { background: #fee2e2; color: #dc2626; }
    .badge-yellow { background: #fef9c3; color: #ca8a04; }
    .issues { list-style: none; }
    .issues li { padding: 6px 0; border-bottom: 1px solid #f1f5f9;
                 font-size: 13px; color: #64748b; }
    .issues li::before { content: "⚠️ "; }
    .footer { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 DataSift Pipeline Report</h1>
    <div class="subtitle">{{ pipeline_name }} · {{ run_timestamp }}</div>
  </div>

  <div class="cards">
    <div class="card">
      <div class="card-value">{{ stats.input_rows }}</div>
      <div class="card-label">Input Rows</div>
    </div>
    <div class="card">
      <div class="card-value">{{ stats.output_rows }}</div>
      <div class="card-label">Output Rows</div>
    </div>
    <div class="card">
      <div class="card-value">{{ stats.enriched_rows }}</div>
      <div class="card-label">Rows Enriched</div>
    </div>
    <div class="card">
      <div class="card-value" style="color: {% if stats.failed_rows > 0 %}#ef4444{% else %}#22c55e{% endif %}">
        {{ stats.failed_rows }}
      </div>
      <div class="card-label">Enrichment Failures</div>
    </div>
    <div class="card">
      <div class="card-value">{{ stats.columns_added }}</div>
      <div class="card-label">Columns Added</div>
    </div>
  </div>

  {% for col, value_counts in column_distributions.items() %}
  <div class="section">
    <h2>Distribution: {{ col }}</h2>
    <table>
      <thead><tr><th>Value</th><th>Count</th><th>Share</th><th></th></tr></thead>
      <tbody>
        {% set total = value_counts.values() | sum %}
        {% for value, count in value_counts.items() %}
        <tr>
          <td>{{ value }}</td>
          <td>{{ count }}</td>
          <td>{{ "%.1f" | format(count / total * 100) }}%</td>
          <td style="width:200px">
            <div class="bar-wrap">
              <div class="bar" style="width: {{ (count / total * 100) | int }}%"></div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endfor %}

  {% if cleaning_issues %}
  <div class="section">
    <h2>Cleaning Notes</h2>
    <ul class="issues">
      {% for issue in cleaning_issues %}
      <li>{{ issue }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  <div class="section">
    <h2>Sample Output (first 10 rows)</h2>
    {{ sample_table }}
  </div>

  <div class="footer">
    Generated by DataSift · {{ run_timestamp }}
  </div>
</body>
</html>
"""


def export(
    df: pd.DataFrame,
    output_dir: str | Path,
    pipeline_name: str,
    enrichment_report,
    cleaning_report,
    enrichment_config: dict,
) -> dict[str, Path]:
    """
    Write enriched CSV, SQLite database, and HTML report to output_dir.
    Returns a dict of {type: path} for each output.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = pipeline_name.lower().replace(" ", "_")

    csv_path = output_dir / f"{safe_name}_{timestamp}.csv"
    db_path = output_dir / f"{safe_name}_{timestamp}.db"
    report_path = output_dir / f"{safe_name}_{timestamp}_report.html"

    # CSV
    df.to_csv(csv_path, index=False)
    log.info(f"Wrote CSV: {csv_path}")

    # SQLite
    table_name = safe_name or "enriched_data"
    with sqlite3.connect(db_path) as conn:
        df.to_sql(table_name, conn, if_exists="replace", index=False)
    log.info(f"Wrote SQLite: {db_path}")

    # HTML Report
    enriched_cols = enrichment_report.columns_added if enrichment_report else []
    col_distributions = {}
    for col in enriched_cols:
        if col in df.columns:
            vc = df[col].value_counts().to_dict()
            col_distributions[col] = vc

    stats = {
        "input_rows": cleaning_report.original_rows if cleaning_report else len(df),
        "output_rows": len(df),
        "enriched_rows": enrichment_report.enriched_rows if enrichment_report else 0,
        "failed_rows": enrichment_report.failed_rows if enrichment_report else 0,
        "columns_added": len(enriched_cols),
    }

    sample_df = df.head(10)
    sample_html = sample_df.to_html(
        index=False,
        classes="",
        border=0,
        escape=True,
    )

    html = Template(REPORT_TEMPLATE).render(
        pipeline_name=pipeline_name,
        run_timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        stats=stats,
        column_distributions=col_distributions,
        cleaning_issues=cleaning_report.issues if cleaning_report else [],
        sample_table=sample_html,
    )

    report_path.write_text(html, encoding="utf-8")
    log.info(f"Wrote HTML report: {report_path}")

    return {"csv": csv_path, "db": db_path, "report": report_path}
